mj:
  discord:
    guild-id: 1112940597846749225
    channel-id: 1112940597846749228
    user-token: MTEwNDY1NDYyNTI1NDE0NjE0OA.GkgdPs.RnDZoQH8nstU5lbq8iOkS9fT9Snzz2xKWgX4Iw
    user-wss: true
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
    bot-token: xxx
  task-store:
    type: redis
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10
spring:
  redis:
    port: 15764
    host: redis-15764.c82.us-east-1-2.ec2.cloud.redislabs.com
    password: 9qqxOYENX5ngPqqx1BaPbnS7tLoBdKwd